/**
 * Katalog instrumen awal.
 *
 * Satu daftar untuk seluruh kelas aset, karena pertanyaan "apa saja yang
 * dilacak sistem ini" harus punya satu jawaban yang bisa dibaca, bukan tersebar
 * di beberapa berkas.
 *
 * Daftar ini keinginan, bukan kebenaran. Simbol bisa berganti nama, kontrak
 * berjangka bisa berpindah, dan bursa menghapus pasangan tanpa pemberitahuan.
 * Karena itu skrip seed memeriksa tiap simbol ke sumbernya lebih dulu dan
 * melaporkan mana yang tidak menjawab, alih-alih memasukkannya diam-diam lalu
 * membiarkannya gagal tiap hari di dalam log.
 */

import type { Market } from './types'
import type { AssetClass } from '@/lib/db/schema'

export interface CatalogueEntry {
  symbol: string
  name: string
  market: Market
  assetClass: AssetClass
  currency: string
  /** Negara atau kawasan, untuk mengelompokkan indeks di antarmuka. */
  region?: string
}

// ---------------------------------------------------------------------------
// Crypto — Binance
// ---------------------------------------------------------------------------

const CRYPTO: CatalogueEntry[] = ([
  ['BTCUSDT', 'Bitcoin'],
  ['ETHUSDT', 'Ethereum'],
  ['BNBUSDT', 'BNB'],
  ['SOLUSDT', 'Solana'],
  ['XRPUSDT', 'XRP'],
  ['ADAUSDT', 'Cardano'],
  ['DOTUSDT', 'Polkadot'],
  ['AVAXUSDT', 'Avalanche'],
  ['POLUSDT', 'Polygon'],
  ['LINKUSDT', 'Chainlink'],
  ['TRXUSDT', 'TRON'],
  ['LTCUSDT', 'Litecoin'],
  ['BCHUSDT', 'Bitcoin Cash'],
  ['ATOMUSDT', 'Cosmos'],
  ['NEARUSDT', 'NEAR Protocol'],
  ['APTUSDT', 'Aptos'],
  ['ARBUSDT', 'Arbitrum'],
  ['OPUSDT', 'Optimism'],
  ['FILUSDT', 'Filecoin'],
  ['ICPUSDT', 'Internet Computer'],
  ['INJUSDT', 'Injective'],
  ['SUIUSDT', 'Sui'],
  ['SEIUSDT', 'Sei'],
  ['TIAUSDT', 'Celestia'],
  ['GRTUSDT', 'The Graph'],
  ['AAVEUSDT', 'Aave'],
  ['UNIUSDT', 'Uniswap'],
  ['LDOUSDT', 'Lido DAO'],
  ['STXUSDT', 'Stacks'],
  ['ALGOUSDT', 'Algorand'],
  ['VETUSDT', 'VeChain'],
  ['HBARUSDT', 'Hedera'],
  ['XLMUSDT', 'Stellar'],
  ['ETCUSDT', 'Ethereum Classic'],
  ['RENDERUSDT', 'Render'],
  ['FETUSDT', 'Artificial Superintelligence'],
] as [string, string][]).map(([symbol, name]) => ({
  symbol,
  name,
  market: 'CRYPTO' as Market,
  assetClass: 'crypto' as AssetClass,
  currency: 'USDT',
}))

// ---------------------------------------------------------------------------
// Emas
// ---------------------------------------------------------------------------

/**
 * Emas didekati dari dua sisi yang sengaja dibiarkan berdampingan.
 *
 * Kontrak berjangka adalah harga acuan dunia dan berhenti di akhir pekan. Token
 * beragun emas berdagang terus tanpa jeda dan membawa risiko penerbitnya
 * sendiri. Keduanya melacak logam yang sama tetapi tidak pernah sama persis,
 * dan selisihnya sendiri adalah informasi.
 */
// ---------------------------------------------------------------------------
// Koin meme
// ---------------------------------------------------------------------------

/**
 * Dipisah dari crypto dengan sengaja.
 *
 * Koin meme tidak punya pendapatan, jadwal unlock yang bermakna, maupun
 * aktivitas jaringan yang menjelaskan harganya. Yang menggerakkannya perhatian
 * orang, dan itu jenis risiko yang berbeda — bukan lebih buruk, tetapi tidak
 * bisa dinilai dengan pertanyaan yang sama. Menaruhnya satu tab dengan Bitcoin
 * membuat keduanya terlihat setara, dan itu yang paling menyesatkan.
 */
const MEMECOIN: CatalogueEntry[] = ([
  ['DOGEUSDT', 'Dogecoin'],
  ['SHIBUSDT', 'Shiba Inu'],
  ['PEPEUSDT', 'Pepe'],
  ['WIFUSDT', 'dogwifhat'],
  ['BONKUSDT', 'Bonk'],
  ['FLOKIUSDT', 'Floki'],
  ['BOMEUSDT', 'Book of Meme'],
  ['MEMEUSDT', 'Memecoin'],
  ['NEIROUSDT', 'Neiro'],
  ['TURBOUSDT', 'Turbo'],
  ['1000SATSUSDT', 'SATS'],
  ['ORDIUSDT', 'ORDI'],
  ['PENGUUSDT', 'Pudgy Penguins'],
  ['ACTUSDT', 'Act I The AI Prophecy'],
  ['PNUTUSDT', 'Peanut the Squirrel'],
  ['TRUMPUSDT', 'OFFICIAL TRUMP'],
  ['1000CATUSDT', "Simon's Cat"],
  ['1MBABYDOGEUSDT', 'Baby Doge Coin'],
  ['PEOPLEUSDT', 'ConstitutionDAO'],
  ['COWUSDT', 'CoW Protocol'],
  ['THEUSDT', 'THE Protocol'],
  ['KAIAUSDT', 'Kaia'],
  ['LUNCUSDT', 'Terra Classic'],
  ['USTCUSDT', 'TerraClassicUSD'],
  ['DOGSUSDT', 'Dogs'],
  ['NOTUSDT', 'Notcoin'],
  ['HMSTRUSDT', 'Hamster Kombat'],
  ['CATIUSDT', 'Catizen'],
  ['PUMPUSDT', 'Big Pump'],
  ['AIXBTUSDT', 'AIXBT by Virtuals'],
  ['VIRTUALUSDT', 'Virtuals Protocol'],
  ['BANANAUSDT', 'Banana Gun'],
  ['SLPUSDT', 'Smooth Love Potion'],
  ['GALAUSDT', 'Gala'],
  ['RAREUSDT', 'SuperRare'],
  ['SUNUSDT', 'Sun Token'],
  ['TROYUSDT', 'Troy'],
  ['DARUSDT', 'Mines of Dalarnia'],
  ['VOXELUSDT', 'Voxies'],
  ['ALPACAUSDT', 'Alpaca Finance'],
] as [string, string][]).map(([symbol, name]) => ({
  symbol,
  name,
  market: 'CRYPTO' as Market,
  assetClass: 'memecoin' as AssetClass,
  currency: 'USDT',
}))

const EMAS: CatalogueEntry[] = [
  { symbol: 'GC=F', name: 'Emas berjangka', market: 'GLOBAL', assetClass: 'emas', currency: 'USD', region: 'Global' },
  { symbol: 'PAXGUSDT', name: 'PAX Gold', market: 'CRYPTO', assetClass: 'emas', currency: 'USDT', region: 'Global' },
  { symbol: 'XAUTUSDT', name: 'Tether Gold', market: 'CRYPTO', assetClass: 'emas', currency: 'USDT', region: 'Global' },
]

// ---------------------------------------------------------------------------
// Komoditi
// ---------------------------------------------------------------------------

const KOMODITI: CatalogueEntry[] = ([
  ['SI=F', 'Perak berjangka'],
  ['HG=F', 'Tembaga berjangka'],
  ['PL=F', 'Platina berjangka'],
  ['PA=F', 'Paladium berjangka'],
  ['CL=F', 'Minyak WTI'],
  ['BZ=F', 'Minyak Brent'],
  ['NG=F', 'Gas alam'],
  ['RB=F', 'Bensin RBOB'],
  ['HO=F', 'Minyak pemanas'],
  ['ZC=F', 'Jagung'],
  ['ZW=F', 'Gandum'],
  ['ZS=F', 'Kedelai'],
  ['ZL=F', 'Minyak kedelai'],
  ['ZM=F', 'Bungkil kedelai'],
  ['ZO=F', 'Gandum oat'],
  ['ZR=F', 'Beras'],
  ['KC=F', 'Kopi'],
  ['SB=F', 'Gula'],
  ['CC=F', 'Kakao'],
  ['CT=F', 'Kapas'],
  ['OJ=F', 'Jus jeruk'],
  ['LE=F', 'Sapi hidup'],
  ['HE=F', 'Babi kurus'],
  // LBS=F dihentikan CME dan Yahoo kini menjawab 404. LBR=F kontrak
  // penggantinya — spesifikasinya berbeda, jadi riwayatnya tidak disambung.
  ['LBR=F', 'Kayu'],
] as [string, string][]).map(([symbol, name]) => ({
  symbol,
  name,
  market: 'GLOBAL' as Market,
  assetClass: 'komoditi' as AssetClass,
  currency: 'USD',
  region: 'Global',
}))

// ---------------------------------------------------------------------------
// Saham
// ---------------------------------------------------------------------------

const SAHAM_IDX: CatalogueEntry[] = ([
  ['BBCA.JK', 'Bank Central Asia'],
  ['BBRI.JK', 'Bank Rakyat Indonesia'],
  ['BMRI.JK', 'Bank Mandiri'],
  ['BBNI.JK', 'Bank Negara Indonesia'],
  ['TLKM.JK', 'Telkom Indonesia'],
  ['ASII.JK', 'Astra International'],
  ['UNVR.JK', 'Unilever Indonesia'],
  ['ICBP.JK', 'Indofood CBP'],
  ['KLBF.JK', 'Kalbe Farma'],
  ['ANTM.JK', 'Aneka Tambang'],
  ['ADRO.JK', 'Adaro Energy'],
  ['GOTO.JK', 'GoTo Gojek Tokopedia'],
  ['AMRT.JK', 'Sumber Alfaria Trijaya'],
  ['INDF.JK', 'Indofood Sukses Makmur'],
  ['CPIN.JK', 'Charoen Pokphand Indonesia'],
  ['UNTR.JK', 'United Tractors'],
  ['PGAS.JK', 'Perusahaan Gas Negara'],
  ['PTBA.JK', 'Bukit Asam'],
  ['INCO.JK', 'Vale Indonesia'],
  ['MDKA.JK', 'Merdeka Copper Gold'],
  ['SMGR.JK', 'Semen Indonesia'],
  ['INTP.JK', 'Indocement Tunggal Prakarsa'],
  ['JPFA.JK', 'Japfa Comfeed Indonesia'],
  ['MYOR.JK', 'Mayora Indah'],
  ['TOWR.JK', 'Sarana Menara Nusantara'],
  ['TBIG.JK', 'Tower Bersama Infrastructure'],
  ['EXCL.JK', 'XL Axiata'],
  ['ISAT.JK', 'Indosat Ooredoo Hutchison'],
  ['BRIS.JK', 'Bank Syariah Indonesia'],
  ['BBTN.JK', 'Bank Tabungan Negara'],
  ['ARTO.JK', 'Bank Jago'],
  ['BUKA.JK', 'Bukalapak'],
  ['EMTK.JK', 'Elang Mahkota Teknologi'],
  ['MNCN.JK', 'Media Nusantara Citra'],
  ['SCMA.JK', 'Surya Citra Media'],
  ['ACES.JK', 'Aspirasi Hidup Indonesia'],
  ['ERAA.JK', 'Erajaya Swasembada'],
  ['MAPI.JK', 'Mitra Adiperkasa'],
  ['SIDO.JK', 'Industri Jamu Sido Muncul'],
  ['KAEF.JK', 'Kimia Farma'],
  ['INKP.JK', 'Indah Kiat Pulp & Paper'],
  ['TKIM.JK', 'Pabrik Kertas Tjiwi Kimia'],
  ['BRPT.JK', 'Barito Pacific'],
  ['TPIA.JK', 'Chandra Asri Pacific'],
  ['MEDC.JK', 'Medco Energi Internasional'],
  ['HRUM.JK', 'Harum Energy'],
  ['ITMG.JK', 'Indo Tambangraya Megah'],
  ['AKRA.JK', 'AKR Corporindo'],
  ['CTRA.JK', 'Ciputra Development'],
  ['BSDE.JK', 'Bumi Serpong Damai'],
  ['PWON.JK', 'Pakuwon Jati'],
  ['SMRA.JK', 'Summarecon Agung'],
  ['JSMR.JK', 'Jasa Marga'],
  ['WIKA.JK', 'Wijaya Karya'],
  ['PTPP.JK', 'PP'],
  ['ADHI.JK', 'Adhi Karya'],
  ['GGRM.JK', 'Gudang Garam'],
  ['HMSP.JK', 'HM Sampoerna'],
  ['AALI.JK', 'Astra Agro Lestari'],
  ['LSIP.JK', 'PP London Sumatra Indonesia'],
  ['DSNG.JK', 'Dharma Satya Nusantara'],
  ['BREN.JK', 'Barito Renewables'],
  ['CUAN.JK', 'Petrindo Jaya Kreasi'],
  ['PTRO.JK', 'Petrosea'],
  ['AMMN.JK', 'Amman Mineral Internasional'],
  ['MBMA.JK', 'Merdeka Battery Materials'],
  ['NCKL.JK', 'Trimegah Bangun Persada'],
  ['TINS.JK', 'Timah'],
  ['BUMI.JK', 'Bumi Resources'],
  ['DEWA.JK', 'Darma Henwa'],
  ['ENRG.JK', 'Energi Mega Persada'],
  ['ADMR.JK', 'Adaro Minerals Indonesia'],
  ['INDY.JK', 'Indika Energy'],
  ['DOID.JK', 'Delta Dunia Makmur'],
  ['ESSA.JK', 'ESSA Industries Indonesia'],
  ['MAPA.JK', 'MAP Aktif Adiperkasa'],
  ['MIKA.JK', 'Mitra Keluarga Karyasehat'],
  ['HEAL.JK', 'Medikaloka Hermina'],
  ['SILO.JK', 'Siloam International Hospitals'],
  ['ASRI.JK', 'Alam Sutera Realty'],
  ['SSIA.JK', 'Surya Semesta Internusa'],
  ['BDMN.JK', 'Bank Danamon Indonesia'],
  ['AUTO.JK', 'Astra Otoparts'],
  ['DRMA.JK', 'Dharma Polimetal'],
  ['SMSM.JK', 'Selamat Sempurna'],
  ['ASSA.JK', 'Adi Sarana Armada'],
  ['BIRD.JK', 'Blue Bird'],
  ['IPCC.JK', 'Indonesia Kendaraan Terminal'],
  ['CLEO.JK', 'Sariguna Primatirta'],
  ['ULTJ.JK', 'Ultrajaya Milk Industry'],
  ['ROTI.JK', 'Nippon Indosari Corpindo'],
  ['GOOD.JK', 'Garudafood Putra Putri Jaya'],
  ['CMRY.JK', 'Cisarua Mountain Dairy'],
  ['AVIA.JK', 'Avia Avian'],
  ['MTEL.JK', 'Dayamitra Telekomunikasi'],
  ['BELI.JK', 'Global Digital Niaga'],
  ['BBYB.JK', 'Bank Neo Commerce'],
  ['BBHI.JK', 'Allo Bank Indonesia'],
  ['AGRO.JK', 'Bank Raya Indonesia'],
  ['BNGA.JK', 'Bank CIMB Niaga'],
  ['BNLI.JK', 'Bank Permata'],
  ['NISP.JK', 'Bank OCBC NISP'],
  ['PNBN.JK', 'Bank Pan Indonesia'],
  ['MEGA.JK', 'Bank Mega'],
  ['BJBR.JK', 'Bank Pembangunan Daerah Jawa Barat dan Banten'],
  ['BJTM.JK', 'Bank Pembangunan Daerah Jawa Timur'],
  ['BTPS.JK', 'Bank BTPN Syariah'],
  ['BBKP.JK', 'Bank KB Bukopin'],
  ['PANI.JK', 'Pantai Indah Kapuk Dua'],
  ['PGEO.JK', 'Pertamina Geothermal Energy'],
  ['ELSA.JK', 'Elnusa'],
  ['RAJA.JK', 'Rukun Raharja'],
  ['WIFI.JK', 'Solusi Sinergi Digital'],
  ['DCII.JK', 'DCI Indonesia'],
  ['CASS.JK', 'Cardig Aero Services'],
  ['IPCM.JK', 'Jasa Armada Indonesia'],
  ['TMAS.JK', 'Temas'],
  ['SMDR.JK', 'Samudera Indonesia'],
  ['WIIM.JK', 'Wismilak Inti Makmur'],
  ['MIDI.JK', 'Midi Utama Indonesia'],
  ['LPPF.JK', 'Matahari Department Store'],
  ['RALS.JK', 'Ramayana Lestari Sentosa'],
  ['HRTA.JK', 'Hartadinata Abadi'],
  ['MARK.JK', 'Mark Dynamics Indonesia'],
  ['KRAS.JK', 'Krakatau Steel'],
  ['FILM.JK', 'MD Pictures'],
  ['SRTG.JK', 'Saratoga Investama Sedaya'],
  ['TOBA.JK', 'TBS Energi Utama'],
  ['ABMM.JK', 'ABM Investama'],
  ['BSSR.JK', 'Baramulti Suksessarana'],
  ['GEMS.JK', 'Golden Energy Mines'],
  ['KKGI.JK', 'Resource Alam Indonesia'],
  ['MBAP.JK', 'Mitrabara Adiperdana'],
  ['BYAN.JK', 'Bayan Resources'],
  ['AADI.JK', 'Adaro Andalan Indonesia'],
  ['DSSA.JK', 'Dian Swastatika Sentosa'],
  ['MLPT.JK', 'Multipolar Technology'],
  ['MTDL.JK', 'Metrodata Electronics'],
  ['BMTR.JK', 'Global Mediacom'],
  ['MAPB.JK', 'MAP Boga Adiperkasa'],
  ['PNLF.JK', 'Panin Financial'],
  ['WTON.JK', 'Wijaya Karya Beton'],
  ['TOTL.JK', 'Total Bangun Persada'],
  ['NRCA.JK', 'Nusa Raya Cipta'],
  ['KIJA.JK', 'Kawasan Industri Jababeka'],
  ['DMAS.JK', 'Puradelta Lestari'],
  ['LPKR.JK', 'Lippo Karawaci'],
  ['APLN.JK', 'Agung Podomoro Land'],
  ['DILD.JK', 'Intiland Development'],
  ['BKSL.JK', 'Sentul City'],
  ['AMAR.JK', 'Bank Amar Indonesia'],
  ['DNET.JK', 'Indoritel Makmur Internasional'],
  ['TAPG.JK', 'Triputra Agro Persada'],
  ['SGRO.JK', 'Sampoerna Agro'],
  ['SSMS.JK', 'Sawit Sumbermas Sarana'],
  ['SIMP.JK', 'Salim Ivomas Pratama'],
  ['TBLA.JK', 'Tunas Baru Lampung'],
  ['ANJT.JK', 'Austindo Nusantara Jaya'],
  ['MAIN.JK', 'Malindo Feedmill'],
  ['CPRO.JK', 'Central Proteina Prima'],
  ['HEXA.JK', 'Hexindo Adiperkasa'],
  ['GJTL.JK', 'Gajah Tunggal'],
  ['IMAS.JK', 'Indomobil Sukses Internasional'],
  ['INDS.JK', 'Indospring'],
  ['MPMX.JK', 'Mitra Pinasthika Mustika'],
  ['SCCO.JK', 'Supreme Cable Manufacturing'],
  ['KBLI.JK', 'KMI Wire and Cable'],
  ['VOKS.JK', 'Voksel Electric'],
  ['JECC.JK', 'Jembo Cable Company'],
  ['ARNA.JK', 'Arwana Citramulia'],
  ['AMFG.JK', 'Asahimas Flat Glass'],
  ['TSPC.JK', 'Tempo Scan Pacific'],
  ['PEHA.JK', 'Phapros'],
  ['MERK.JK', 'Merck Indonesia'],
  ['PYFA.JK', 'Pyridam Farma'],
  ['DVLA.JK', 'Darya-Varia Laboratoria'],
  ['SOHO.JK', 'Soho Global Health'],
  ['PRDA.JK', 'Prodia Widyahusada'],
  ['SAME.JK', 'Sarana Meditama Metropolitan'],
  ['BMHS.JK', 'Bundamedik'],
  ['INAF.JK', 'Indofarma'],
  ['PSAB.JK', 'J Resources Asia Pasifik'],
  ['ARCI.JK', 'Archi Indonesia'],
  ['BRMS.JK', 'Bumi Resources Minerals'],
  ['NICL.JK', 'PAM Mineral'],
  ['ZINC.JK', 'Kapuas Prima Coal'],
  ['IFSH.JK', 'Ifishdeco'],
  ['SMBR.JK', 'Semen Baturaja'],
  ['INTD.JK', 'Inter Delta'],
  ['MSIN.JK', 'MNC Digital Entertainment'],
  ['BFIN.JK', 'BFI Finance Indonesia'],
  ['ADMF.JK', 'Adira Dinamika Multi Finance'],
  ['BBLD.JK', 'Buana Finance'],
  ['WOMF.JK', 'Wahana Ottomitra Multiartha'],
  ['SMMA.JK', 'Sinar Mas Multiartha'],
  ['LIFE.JK', 'Asuransi Jiwa Sinarmas MSIG'],
  ['TUGU.JK', 'Asuransi Tugu Pratama Indonesia'],
  ['PNIN.JK', 'Paninvest'],
  ['JRPT.JK', 'Jaya Real Property'],
  ['CTBN.JK', 'Citra Tubindo'],
  ['MCOL.JK', 'Prima Andalan Mandiri'],
  ['PTPW.JK', 'Pratama Widya'],
  ['RATU.JK', 'Raharja Energi Cepu'],
  ['CDIA.JK', 'Chandra Daya Investasi'],
  ['COAL.JK', 'Black Diamond Resources'],
  ['FAPA.JK', 'FAP Agri'],
  ['STAA.JK', 'Sumber Tani Agung Resources'],
  ['NSSS.JK', 'Nusantara Sawit Sejahtera'],
  ['UNIQ.JK', 'Ulima Nitra'],
  ['OASA.JK', 'Maharaksa Biru Energi'],
  ['BUVA.JK', 'Bukit Uluwatu Villa'],
  ['MINA.JK', 'Sanurhasta Mitra'],
  ['DATA.JK', 'Remala Abadi'],
  ['SOLA.JK', 'Xolare RCR Energy'],
  ['HUMI.JK', 'Humpuss Maritim Internasional'],
  ['SINI.JK', 'Singaraja Putra'],
  ['KOKA.JK', 'Koka Indonesia'],
  ['MSJA.JK', 'Multi Spunindo Jaya'],
  ['CHEM.JK', 'Chemstar Indonesia'],
  ['TRIN.JK', 'Perintis Triniti Properti'],
  ['NETV.JK', 'MDTV Media Technologies'],
  ['PADI.JK', 'Minna Padi Investama Sekuritas'],
  ['LABA.JK', 'Green Power Group'],
] as [string, string][]).map(([symbol, name]) => ({
  symbol,
  name,
  market: 'IDX' as Market,
  assetClass: 'saham' as AssetClass,
  currency: 'IDR',
  region: 'Indonesia',
}))

const SAHAM_US: CatalogueEntry[] = ([
  // Sekitar seratus emiten berkapitalisasi terbesar. Delapan tidak cukup untuk
  // menguji normalisasi sektor: persentil valuasi butuh penampang lintang.
  ['AAPL', 'Apple'],
  ['MSFT', 'Microsoft'],
  ['NVDA', 'NVIDIA'],
  ['GOOGL', 'Alphabet'],
  ['AMZN', 'Amazon'],
  ['META', 'Meta Platforms'],
  ['TSLA', 'Tesla'],
  ['AVGO', 'Broadcom'],
  ['BRK-B', 'Berkshire Hathaway'],
  ['LLY', 'Eli Lilly'],
  ['JPM', 'JPMorgan Chase'],
  ['V', 'Visa'],
  ['MA', 'Mastercard'],
  ['XOM', 'Exxon Mobil'],
  ['UNH', 'UnitedHealth'],
  ['JNJ', 'Johnson & Johnson'],
  ['PG', 'Procter & Gamble'],
  ['COST', 'Costco'],
  ['HD', 'Home Depot'],
  ['ABBV', 'AbbVie'],
  ['WMT', 'Walmart'],
  ['MRK', 'Merck'],
  ['NFLX', 'Netflix'],
  ['KO', 'Coca-Cola'],
  ['PEP', 'PepsiCo'],
  ['ADBE', 'Adobe'],
  ['CRM', 'Salesforce'],
  ['ORCL', 'Oracle'],
  ['AMD', 'AMD'],
  ['CSCO', 'Cisco'],
  ['ACN', 'Accenture'],
  ['MCD', "McDonald's"],
  ['TMO', 'Thermo Fisher'],
  ['ABT', 'Abbott'],
  ['LIN', 'Linde'],
  ['CVX', 'Chevron'],
  ['INTC', 'Intel'],
  ['QCOM', 'Qualcomm'],
  ['TXN', 'Texas Instruments'],
  ['INTU', 'Intuit'],
  ['IBM', 'IBM'],
  ['GE', 'General Electric'],
  ['CAT', 'Caterpillar'],
  ['BA', 'Boeing'],
  ['HON', 'Honeywell'],
  ['UPS', 'UPS'],
  ['RTX', 'RTX'],
  ['LMT', 'Lockheed Martin'],
  ['DE', 'Deere'],
  ['NKE', 'Nike'],
  ['SBUX', 'Starbucks'],
  ['LOW', "Lowe's"],
  ['TGT', 'Target'],
  ['DIS', 'Disney'],
  ['CMCSA', 'Comcast'],
  ['VZ', 'Verizon'],
  ['T', 'AT&T'],
  ['TMUS', 'T-Mobile'],
  ['BAC', 'Bank of America'],
  ['WFC', 'Wells Fargo'],
  ['C', 'Citigroup'],
  ['GS', 'Goldman Sachs'],
  ['MS', 'Morgan Stanley'],
  ['AXP', 'American Express'],
  ['BLK', 'BlackRock'],
  ['SCHW', 'Charles Schwab'],
  ['PNC', 'PNC Financial'],
  ['USB', 'U.S. Bancorp'],
  ['PFE', 'Pfizer'],
  ['BMY', 'Bristol-Myers Squibb'],
  ['AMGN', 'Amgen'],
  ['GILD', 'Gilead Sciences'],
  ['CVS', 'CVS Health'],
  ['MDT', 'Medtronic'],
  ['DHR', 'Danaher'],
  ['ISRG', 'Intuitive Surgical'],
  ['SYK', 'Stryker'],
  ['BSX', 'Boston Scientific'],
  ['VRTX', 'Vertex'],
  ['REGN', 'Regeneron'],
  ['MU', 'Micron'],
  ['AMAT', 'Applied Materials'],
  ['LRCX', 'Lam Research'],
  ['KLAC', 'KLA'],
  ['ADI', 'Analog Devices'],
  ['NOW', 'ServiceNow'],
  ['PANW', 'Palo Alto Networks'],
  ['SNPS', 'Synopsys'],
  ['CDNS', 'Cadence'],
  ['UBER', 'Uber'],
  ['ABNB', 'Airbnb'],
  ['PYPL', 'PayPal'],
  ['SPGI', 'S&P Global'],
  ['CME', 'CME Group'],
  ['ICE', 'Intercontinental Exchange'],
  ['MMM', '3M'],
  ['COP', 'ConocoPhillips'],
  ['SLB', 'SLB'],
  ['EOG', 'EOG Resources'],
  ['NEE', 'NextEra Energy'],
  ['DUK', 'Duke Energy'],
  ['SO', 'Southern Company'],
  ['PLD', 'Prologis'],
  ['AMT', 'American Tower'],
  ['MO', 'Altria'],
  ['MDLZ', 'Mondelez'],
  ['CL', 'Colgate-Palmolive'],
  ['KMB', 'Kimberly-Clark'],
  ['PLTR', 'Palantir Technologies'],
  ['ARM', 'Arm Holdings'],
  ['SMCI', 'Super Micro Computer'],
  ['DELL', 'Dell Technologies'],
  ['APP', 'AppLovin'],
  ['SNOW', 'Snowflake'],
  ['NET', 'Cloudflare'],
  ['DDOG', 'Datadog'],
  ['CRWD', 'CrowdStrike'],
  ['ZS', 'Zscaler'],
  ['COIN', 'Coinbase Global'],
  ['MSTR', 'MicroStrategy'],
  ['HOOD', 'Robinhood Markets'],
  ['SOFI', 'SoFi Technologies'],
  ['MARA', 'MARA Holdings'],
  ['RIOT', 'Riot Platforms'],
  ['CLSK', 'CleanSpark'],
  ['IREN', 'IREN'],
  ['RIVN', 'Rivian Automotive'],
  ['LCID', 'Lucid Group'],
  ['BABA', 'Alibaba Group'],
  ['PDD', 'PDD Holdings'],
  ['JD', 'JD.com'],
  ['NIO', 'NIO'],
  ['XPEV', 'XPeng'],
  ['LI', 'Li Auto'],
  ['TSM', 'TSMC (ADR)'],
  ['ADP', 'Automatic Data Processing'],
  ['BKNG', 'Booking Holdings'],
  ['MELI', 'MercadoLibre'],
  ['SHOP', 'Shopify'],
  ['XYZ', 'Block'],
  ['SPOT', 'Spotify'],
  ['TTD', 'The Trade Desk'],
  ['ROKU', 'Roku'],
  ['ZM', 'Zoom Communications'],
  ['DOCU', 'DocuSign'],
  ['TEAM', 'Atlassian'],
  ['WDAY', 'Workday'],
  ['ADSK', 'Autodesk'],
  ['FTNT', 'Fortinet'],
  ['MRVL', 'Marvell Technology'],
  ['ON', 'ON Semiconductor'],
  ['NXPI', 'NXP Semiconductors'],
  ['MCHP', 'Microchip Technology'],
  ['ANET', 'Arista Networks'],
  ['HPQ', 'HP Inc.'],
  ['WDC', 'Western Digital'],
  ['STX', 'Seagate Technology'],
  ['F', 'Ford Motor'],
  ['GM', 'General Motors'],
  ['SE', 'Sea Limited'],
  ['GRAB', 'Grab Holdings'],
  ['CPNG', 'Coupang'],
  ['NU', 'Nu Holdings'],
  ['RBLX', 'Roblox'],
  ['DKNG', 'DraftKings'],
  ['PINS', 'Pinterest'],
  ['SNAP', 'Snap'],
  ['RDDT', 'Reddit'],
  ['DASH', 'DoorDash'],
  ['LYFT', 'Lyft'],
  ['EBAY', 'eBay'],
  ['ETSY', 'Etsy'],
  ['LULU', 'Lululemon'],
  ['CMG', 'Chipotle'],
  ['YUM', 'Yum! Brands'],
  ['MAR', 'Marriott'],
  ['HLT', 'Hilton'],
  ['DAL', 'Delta Air Lines'],
  ['UAL', 'United Airlines'],
  ['AAL', 'American Airlines'],
  ['CCL', 'Carnival'],
  ['RCL', 'Royal Caribbean'],
  ['FDX', 'FedEx'],
  ['UNP', 'Union Pacific'],
  ['WM', 'Waste Management'],
  ['GD', 'General Dynamics'],
  ['NOC', 'Northrop Grumman'],
  ['HCA', 'HCA Healthcare'],
  ['CI', 'Cigna'],
  ['ELV', 'Elevance Health'],
  ['ZTS', 'Zoetis'],
  ['MRNA', 'Moderna'],
  ['BIIB', 'Biogen'],
  ['TJX', 'TJX Companies'],
  ['ROST', 'Ross Stores'],
  ['DG', 'Dollar General'],
  ['KR', 'Kroger'],
  ['KHC', 'Kraft Heinz'],
  ['HSY', 'Hershey'],
  ['PM', 'Philip Morris'],
  ['OXY', 'Occidental Petroleum'],
  ['MPC', 'Marathon Petroleum'],
  ['PSX', 'Phillips 66'],
  ['VLO', 'Valero Energy'],
  ['KMI', 'Kinder Morgan'],
  ['FCX', 'Freeport-McMoRan'],
  ['NEM', 'Newmont'],
  ['NUE', 'Nucor'],
  ['SHW', 'Sherwin-Williams'],
  ['EQIX', 'Equinix'],
  ['O', 'Realty Income'],
  ['SPG', 'Simon Property'],
  ['MET', 'MetLife'],
  ['PRU', 'Prudential Financial'],
  ['AIG', 'AIG'],
  ['CB', 'Chubb'],
  ['PGR', 'Progressive'],
  ['COF', 'Capital One'],
  ['BX', 'Blackstone'],
  ['KKR', 'KKR'],
  ['APO', 'Apollo Global'],
  ['MCO', "Moody's"],
  ['GEV', 'GE Vernova'],
  ['VST', 'Vistra'],
  ['CEG', 'Constellation Energy'],
  ['VRT', 'Vertiv'],
  ['IONQ', 'IonQ'],
  ['RGTI', 'Rigetti Computing'],
  ['QBTS', 'D-Wave Quantum'],
  ['OKLO', 'Oklo'],
  ['SMR', 'NuScale Power'],
  ['HIMS', 'Hims & Hers Health'],
  ['AFRM', 'Affirm'],
  ['UPST', 'Upstart'],
  ['SOUN', 'SoundHound AI'],
  ['BBAI', 'BigBear.ai'],
  ['ACHR', 'Archer Aviation'],
  ['JOBY', 'Joby Aviation'],
  ['RKLB', 'Rocket Lab'],
  ['ASTS', 'AST SpaceMobile'],
  ['CVNA', 'Carvana'],
  ['DUOL', 'Duolingo'],
  ['CELH', 'Celsius Holdings'],
  ['ENPH', 'Enphase Energy'],
  ['FSLR', 'First Solar'],
  ['PLUG', 'Plug Power'],
  ['GME', 'GameStop'],
  ['AMC', 'AMC Entertainment'],
  ['TTWO', 'Take-Two Interactive'],
  ['WBD', 'Warner Bros. Discovery'],
  ['CHTR', 'Charter Communications'],
  ['NVO', 'Novo Nordisk (ADR)'],
  ['ASML', 'ASML (ADR)'],
  ['TM', 'Toyota (ADR)'],
  ['SONY', 'Sony (ADR)'],
  ['BIDU', 'Baidu'],
  ['NTES', 'NetEase'],
  ['TCOM', 'Trip.com'],
  ['BILI', 'Bilibili'],
  ['BEKE', 'KE Holdings'],
  ['TME', 'Tencent Music'],
  ['ZTO', 'ZTO Express'],
  ['YUMC', 'Yum China'],
  ['FUTU', 'Futu Holdings'],
  ['TAL', 'TAL Education'],
  ['EDU', 'New Oriental Education'],
  ['VIPS', 'Vipshop'],
  ['HTHT', 'H World Group'],
  ['QFIN', 'Qifu Technology'],
  ['MNSO', 'MINISO'],
  ['GDS', 'GDS Holdings'],
] as [string, string][]).map(([symbol, name]) => ({
  symbol,
  name,
  market: 'US' as Market,
  assetClass: 'saham' as AssetClass,
  currency: 'USD',
  region: 'Amerika Serikat',
}))

// ---------------------------------------------------------------------------
// Saham internasional di luar Amerika
// ---------------------------------------------------------------------------

/**
 * Bursa di luar AS ditulis sebagai satu daftar berlabel negara, bukan satu
 * konstanta per negara. Yang membedakan mereka cuma akhiran simbol dan zona
 * waktunya; memecahnya jadi sepuluh konstanta hanya menambah tempat untuk lupa
 * memasukkan salah satunya ke katalog akhir.
 *
 * Akhiran Yahoo menentukan bursanya: .T Tokyo, .HK Hong Kong, .L London,
 * .DE Xetra, .PA Paris, .AS Amsterdam, .SW Swiss, .MI Milan, .KS Korea,
 * .KQ KOSDAQ, .NS India, .AX Australia, .SI Singapura, .TW Taiwan, .SS
 * Shanghai, .SZ Shenzhen.
 */
const SAHAM_INTERNASIONAL: CatalogueEntry[] = ([
  ['7203.T', 'Toyota Motor', 'JPY', 'Jepang'],
  ['6758.T', 'Sony Group', 'JPY', 'Jepang'],
  ['6861.T', 'Keyence', 'JPY', 'Jepang'],
  ['8306.T', 'Mitsubishi UFJ Financial', 'JPY', 'Jepang'],
  ['9984.T', 'SoftBank Group', 'JPY', 'Jepang'],
  ['7267.T', 'Honda Motor', 'JPY', 'Jepang'],
  ['4063.T', 'Shin-Etsu Chemical', 'JPY', 'Jepang'],
  ['9432.T', 'Nippon Telegraph & Telephone', 'JPY', 'Jepang'],
  ['8035.T', 'Tokyo Electron', 'JPY', 'Jepang'],
  ['6501.T', 'Hitachi', 'JPY', 'Jepang'],
  ['7974.T', 'Nintendo', 'JPY', 'Jepang'],
  ['4502.T', 'Takeda Pharmaceutical', 'JPY', 'Jepang'],
  ['8058.T', 'Mitsubishi Corporation', 'JPY', 'Jepang'],
  ['6098.T', 'Recruit Holdings', 'JPY', 'Jepang'],

  ['0700.HK', 'Tencent Holdings', 'HKD', 'Hong Kong'],
  ['9988.HK', 'Alibaba Group', 'HKD', 'Hong Kong'],
  ['0941.HK', 'China Mobile', 'HKD', 'Hong Kong'],
  ['1299.HK', 'AIA Group', 'HKD', 'Hong Kong'],
  ['3690.HK', 'Meituan', 'HKD', 'Hong Kong'],
  ['0388.HK', 'Hong Kong Exchanges', 'HKD', 'Hong Kong'],
  ['1810.HK', 'Xiaomi', 'HKD', 'Hong Kong'],
  ['2318.HK', 'Ping An Insurance', 'HKD', 'Hong Kong'],
  ['0005.HK', 'HSBC Holdings', 'HKD', 'Hong Kong'],
  ['1398.HK', 'ICBC', 'HKD', 'Hong Kong'],
  ['0939.HK', 'China Construction Bank', 'HKD', 'Hong Kong'],
  ['9618.HK', 'JD.com', 'HKD', 'Hong Kong'],
  ['0883.HK', 'CNOOC', 'HKD', 'Hong Kong'],

  ['SHEL.L', 'Shell', 'GBP', 'Inggris'],
  ['AZN.L', 'AstraZeneca', 'GBP', 'Inggris'],
  ['HSBA.L', 'HSBC', 'GBP', 'Inggris'],
  ['ULVR.L', 'Unilever', 'GBP', 'Inggris'],
  ['BP.L', 'BP', 'GBP', 'Inggris'],
  ['GSK.L', 'GSK', 'GBP', 'Inggris'],
  ['RIO.L', 'Rio Tinto', 'GBP', 'Inggris'],
  ['BATS.L', 'British American Tobacco', 'GBP', 'Inggris'],
  ['DGE.L', 'Diageo', 'GBP', 'Inggris'],

  ['SAP.DE', 'SAP', 'EUR', 'Jerman'],
  ['SIE.DE', 'Siemens', 'EUR', 'Jerman'],
  ['ALV.DE', 'Allianz', 'EUR', 'Jerman'],
  ['DTE.DE', 'Deutsche Telekom', 'EUR', 'Jerman'],
  ['MBG.DE', 'Mercedes-Benz Group', 'EUR', 'Jerman'],
  ['BMW.DE', 'BMW', 'EUR', 'Jerman'],
  ['BAS.DE', 'BASF', 'EUR', 'Jerman'],
  ['BAYN.DE', 'Bayer', 'EUR', 'Jerman'],

  ['MC.PA', 'LVMH', 'EUR', 'Prancis'],
  ['OR.PA', "L'Oreal", 'EUR', 'Prancis'],
  ['TTE.PA', 'TotalEnergies', 'EUR', 'Prancis'],
  ['SAN.PA', 'Sanofi', 'EUR', 'Prancis'],
  ['AIR.PA', 'Airbus', 'EUR', 'Prancis'],
  ['SU.PA', 'Schneider Electric', 'EUR', 'Prancis'],
  ['BNP.PA', 'BNP Paribas', 'EUR', 'Prancis'],
  ['AI.PA', 'Air Liquide', 'EUR', 'Prancis'],

  ['ASML.AS', 'ASML Holding', 'EUR', 'Belanda'],
  ['INGA.AS', 'ING Groep', 'EUR', 'Belanda'],
  ['AD.AS', 'Ahold Delhaize', 'EUR', 'Belanda'],
  ['HEIA.AS', 'Heineken', 'EUR', 'Belanda'],
  ['PHIA.AS', 'Philips', 'EUR', 'Belanda'],

  ['NESN.SW', 'Nestle', 'CHF', 'Swiss'],
  // ROG.SW (Genussschein) tidak lagi tersedia di Yahoo. RO.SW saham pembawa
  // Roche — efek yang berbeda dengan harga berbeda, jadi riwayatnya terpisah.
  ['RO.SW', 'Roche', 'CHF', 'Swiss'],
  ['NOVN.SW', 'Novartis', 'CHF', 'Swiss'],
  ['UBSG.SW', 'UBS Group', 'CHF', 'Swiss'],
  ['ZURN.SW', 'Zurich Insurance', 'CHF', 'Swiss'],

  ['ENI.MI', 'Eni', 'EUR', 'Italia'],
  ['ISP.MI', 'Intesa Sanpaolo', 'EUR', 'Italia'],
  ['UCG.MI', 'UniCredit', 'EUR', 'Italia'],
  ['ENEL.MI', 'Enel', 'EUR', 'Italia'],

  ['005930.KS', 'Samsung Electronics', 'KRW', 'Korea Selatan'],
  ['000660.KS', 'SK Hynix', 'KRW', 'Korea Selatan'],
  ['005380.KS', 'Hyundai Motor', 'KRW', 'Korea Selatan'],
  ['051910.KS', 'LG Chem', 'KRW', 'Korea Selatan'],
  ['035420.KS', 'NAVER', 'KRW', 'Korea Selatan'],
  ['207940.KS', 'Samsung Biologics', 'KRW', 'Korea Selatan'],
  ['005490.KS', 'POSCO Holdings', 'KRW', 'Korea Selatan'],
  ['035720.KS', 'Kakao', 'KRW', 'Korea Selatan'],

  ['2330.TW', 'TSMC', 'TWD', 'Taiwan'],
  ['2317.TW', 'Hon Hai Precision', 'TWD', 'Taiwan'],
  ['2454.TW', 'MediaTek', 'TWD', 'Taiwan'],

  ['RELIANCE.NS', 'Reliance Industries', 'INR', 'India'],
  ['TCS.NS', 'Tata Consultancy Services', 'INR', 'India'],
  ['HDFCBANK.NS', 'HDFC Bank', 'INR', 'India'],
  ['INFY.NS', 'Infosys', 'INR', 'India'],
  ['ICICIBANK.NS', 'ICICI Bank', 'INR', 'India'],
  ['HINDUNILVR.NS', 'Hindustan Unilever', 'INR', 'India'],
  ['BHARTIARTL.NS', 'Bharti Airtel', 'INR', 'India'],
  ['ITC.NS', 'ITC', 'INR', 'India'],
  ['SBIN.NS', 'State Bank of India', 'INR', 'India'],
  ['LT.NS', 'Larsen & Toubro', 'INR', 'India'],

  ['BHP.AX', 'BHP Group', 'AUD', 'Australia'],
  ['CBA.AX', 'Commonwealth Bank', 'AUD', 'Australia'],
  ['CSL.AX', 'CSL', 'AUD', 'Australia'],
  ['NAB.AX', 'National Australia Bank', 'AUD', 'Australia'],
  ['WBC.AX', 'Westpac Banking', 'AUD', 'Australia'],
  ['ANZ.AX', 'ANZ Group', 'AUD', 'Australia'],
  ['WES.AX', 'Wesfarmers', 'AUD', 'Australia'],
  ['MQG.AX', 'Macquarie Group', 'AUD', 'Australia'],

  ['D05.SI', 'DBS Group', 'SGD', 'Singapura'],
  ['O39.SI', 'OCBC', 'SGD', 'Singapura'],
  ['U11.SI', 'United Overseas Bank', 'SGD', 'Singapura'],
  ['Z74.SI', 'Singtel', 'SGD', 'Singapura'],
  ['C6L.SI', 'Singapore Airlines', 'SGD', 'Singapura'],

  ['600519.SS', 'Kweichow Moutai', 'CNY', 'China'],
  ['601318.SS', 'Ping An Insurance (A)', 'CNY', 'China'],
  ['600036.SS', 'China Merchants Bank', 'CNY', 'China'],
  ['601398.SS', 'ICBC (A)', 'CNY', 'China'],
  ['601288.SS', 'Agricultural Bank of China', 'CNY', 'China'],
  ['601988.SS', 'Bank of China (A)', 'CNY', 'China'],
  ['601857.SS', 'PetroChina (A)', 'CNY', 'China'],
  ['600028.SS', 'Sinopec (A)', 'CNY', 'China'],
  ['600900.SS', 'China Yangtze Power', 'CNY', 'China'],
  ['601899.SS', 'Zijin Mining (A)', 'CNY', 'China'],
  ['600276.SS', 'Jiangsu Hengrui Pharmaceuticals', 'CNY', 'China'],
  ['601012.SS', 'LONGi Green Energy', 'CNY', 'China'],
  ['600030.SS', 'CITIC Securities', 'CNY', 'China'],
  ['601166.SS', 'Industrial Bank', 'CNY', 'China'],
  ['600887.SS', 'Inner Mongolia Yili', 'CNY', 'China'],
  ['601088.SS', 'China Shenhua (A)', 'CNY', 'China'],
  ['600309.SS', 'Wanhua Chemical', 'CNY', 'China'],
  ['688981.SS', 'SMIC (A)', 'CNY', 'China'],
  ['601138.SS', 'Foxconn Industrial Internet', 'CNY', 'China'],
  ['300750.SZ', 'CATL', 'CNY', 'China'],
  ['002594.SZ', 'BYD (A)', 'CNY', 'China'],
  ['000858.SZ', 'Wuliangye Yibin', 'CNY', 'China'],
  ['000333.SZ', 'Midea Group', 'CNY', 'China'],
  ['000651.SZ', 'Gree Electric', 'CNY', 'China'],
  ['002415.SZ', 'Hikvision', 'CNY', 'China'],
  ['300059.SZ', 'East Money Information', 'CNY', 'China'],
  ['000001.SZ', 'Ping An Bank', 'CNY', 'China'],
  ['300760.SZ', 'Mindray Medical', 'CNY', 'China'],
  ['002475.SZ', 'Luxshare Precision', 'CNY', 'China'],
  ['000725.SZ', 'BOE Technology', 'CNY', 'China'],
  ['002714.SZ', 'Muyuan Foods', 'CNY', 'China'],
  ['300124.SZ', 'Shenzhen Inovance', 'CNY', 'China'],
  ['000568.SZ', 'Luzhou Laojiao', 'CNY', 'China'],

  ['1211.HK', 'BYD Company', 'HKD', 'Hong Kong'],
  ['2015.HK', 'Li Auto', 'HKD', 'Hong Kong'],
  ['9868.HK', 'XPeng', 'HKD', 'Hong Kong'],
  ['9866.HK', 'NIO', 'HKD', 'Hong Kong'],
  ['9888.HK', 'Baidu', 'HKD', 'Hong Kong'],
  ['9999.HK', 'NetEase', 'HKD', 'Hong Kong'],
  ['1024.HK', 'Kuaishou Technology', 'HKD', 'Hong Kong'],
  ['0981.HK', 'SMIC', 'HKD', 'Hong Kong'],
  ['2020.HK', 'ANTA Sports', 'HKD', 'Hong Kong'],
  ['0386.HK', 'Sinopec', 'HKD', 'Hong Kong'],
  ['0857.HK', 'PetroChina', 'HKD', 'Hong Kong'],
  ['3988.HK', 'Bank of China', 'HKD', 'Hong Kong'],
  ['2628.HK', 'China Life Insurance', 'HKD', 'Hong Kong'],
  ['0001.HK', 'CK Hutchison', 'HKD', 'Hong Kong'],
  ['0016.HK', 'Sun Hung Kai Properties', 'HKD', 'Hong Kong'],
  ['0027.HK', 'Galaxy Entertainment', 'HKD', 'Hong Kong'],
  ['1928.HK', 'Sands China', 'HKD', 'Hong Kong'],
  ['6618.HK', 'JD Health', 'HKD', 'Hong Kong'],
  ['9961.HK', 'Trip.com Group', 'HKD', 'Hong Kong'],
  ['0175.HK', 'Geely Automobile', 'HKD', 'Hong Kong'],
  ['0992.HK', 'Lenovo Group', 'HKD', 'Hong Kong'],
  ['0762.HK', 'China Unicom', 'HKD', 'Hong Kong'],
  ['0728.HK', 'China Telecom', 'HKD', 'Hong Kong'],
  ['2382.HK', 'Sunny Optical', 'HKD', 'Hong Kong'],
  ['0268.HK', 'Kingdee International', 'HKD', 'Hong Kong'],
  ['9633.HK', 'Nongfu Spring', 'HKD', 'Hong Kong'],
  ['6690.HK', 'Haier Smart Home', 'HKD', 'Hong Kong'],
  ['0291.HK', 'China Resources Beer', 'HKD', 'Hong Kong'],
  ['2319.HK', 'China Mengniu Dairy', 'HKD', 'Hong Kong'],
  ['1876.HK', 'Budweiser APAC', 'HKD', 'Hong Kong'],
  ['0002.HK', 'CLP Holdings', 'HKD', 'Hong Kong'],
  ['0066.HK', 'MTR Corporation', 'HKD', 'Hong Kong'],
  ['0823.HK', 'Link REIT', 'HKD', 'Hong Kong'],
  ['6862.HK', 'Haidilao', 'HKD', 'Hong Kong'],
  ['9626.HK', 'Bilibili', 'HKD', 'Hong Kong'],
  ['2269.HK', 'WuXi Biologics', 'HKD', 'Hong Kong'],
  ['1177.HK', 'Sino Biopharmaceutical', 'HKD', 'Hong Kong'],
  ['0288.HK', 'WH Group', 'HKD', 'Hong Kong'],
  ['2899.HK', 'Zijin Mining', 'HKD', 'Hong Kong'],
  ['1088.HK', 'China Shenhua Energy', 'HKD', 'Hong Kong'],
  ['9992.HK', 'Pop Mart', 'HKD', 'Hong Kong'],

  ['373220.KS', 'LG Energy Solution', 'KRW', 'Korea Selatan'],
  ['000270.KS', 'Kia', 'KRW', 'Korea Selatan'],
  ['068270.KS', 'Celltrion', 'KRW', 'Korea Selatan'],
  ['105560.KS', 'KB Financial Group', 'KRW', 'Korea Selatan'],
  ['055550.KS', 'Shinhan Financial Group', 'KRW', 'Korea Selatan'],
  ['086790.KS', 'Hana Financial Group', 'KRW', 'Korea Selatan'],
  ['012330.KS', 'Hyundai Mobis', 'KRW', 'Korea Selatan'],
  ['028260.KS', 'Samsung C&T', 'KRW', 'Korea Selatan'],
  ['006400.KS', 'Samsung SDI', 'KRW', 'Korea Selatan'],
  ['066570.KS', 'LG Electronics', 'KRW', 'Korea Selatan'],
  ['003550.KS', 'LG Corp', 'KRW', 'Korea Selatan'],
  ['034730.KS', 'SK Inc', 'KRW', 'Korea Selatan'],
  ['017670.KS', 'SK Telecom', 'KRW', 'Korea Selatan'],
  ['030200.KS', 'KT Corp', 'KRW', 'Korea Selatan'],
  ['015760.KS', 'Korea Electric Power', 'KRW', 'Korea Selatan'],
  ['032830.KS', 'Samsung Life Insurance', 'KRW', 'Korea Selatan'],
  ['012450.KS', 'Hanwha Aerospace', 'KRW', 'Korea Selatan'],
  ['329180.KS', 'HD Hyundai Heavy Industries', 'KRW', 'Korea Selatan'],
  ['009540.KS', 'HD Korea Shipbuilding', 'KRW', 'Korea Selatan'],
  ['042660.KS', 'Hanwha Ocean', 'KRW', 'Korea Selatan'],
  ['010140.KS', 'Samsung Heavy Industries', 'KRW', 'Korea Selatan'],
  ['034020.KS', 'Doosan Enerbility', 'KRW', 'Korea Selatan'],
  ['010130.KS', 'Korea Zinc', 'KRW', 'Korea Selatan'],
  ['096770.KS', 'SK Innovation', 'KRW', 'Korea Selatan'],
  ['011200.KS', 'HMM', 'KRW', 'Korea Selatan'],
  ['323410.KS', 'KakaoBank', 'KRW', 'Korea Selatan'],
  ['352820.KS', 'HYBE', 'KRW', 'Korea Selatan'],
  ['259960.KS', 'Krafton', 'KRW', 'Korea Selatan'],
  ['036570.KS', 'NCSoft', 'KRW', 'Korea Selatan'],
  ['018260.KS', 'Samsung SDS', 'KRW', 'Korea Selatan'],
  ['009150.KS', 'Samsung Electro-Mechanics', 'KRW', 'Korea Selatan'],
  ['247540.KQ', 'EcoPro BM', 'KRW', 'Korea Selatan'],
  ['086520.KQ', 'EcoPro', 'KRW', 'Korea Selatan'],
  ['196170.KQ', 'Alteogen', 'KRW', 'Korea Selatan'],
  ['041510.KQ', 'SM Entertainment', 'KRW', 'Korea Selatan'],
  ['035900.KQ', 'JYP Entertainment', 'KRW', 'Korea Selatan'],

  ['9983.T', 'Fast Retailing', 'JPY', 'Jepang'],
  ['8316.T', 'Sumitomo Mitsui Financial', 'JPY', 'Jepang'],
  ['6367.T', 'Daikin Industries', 'JPY', 'Jepang'],
  ['6857.T', 'Advantest', 'JPY', 'Jepang'],
  ['7011.T', 'Mitsubishi Heavy Industries', 'JPY', 'Jepang'],
  ['8001.T', 'Itochu', 'JPY', 'Jepang'],
  ['9433.T', 'KDDI', 'JPY', 'Jepang'],
  ['6981.T', 'Murata Manufacturing', 'JPY', 'Jepang'],
  ['4661.T', 'Oriental Land', 'JPY', 'Jepang'],

  ['2308.TW', 'Delta Electronics', 'TWD', 'Taiwan'],
  ['2303.TW', 'United Microelectronics', 'TWD', 'Taiwan'],
  ['3711.TW', 'ASE Technology', 'TWD', 'Taiwan'],
  ['2881.TW', 'Fubon Financial', 'TWD', 'Taiwan'],
  ['2882.TW', 'Cathay Financial', 'TWD', 'Taiwan'],
  ['2603.TW', 'Evergreen Marine', 'TWD', 'Taiwan'],
  ['2412.TW', 'Chunghwa Telecom', 'TWD', 'Taiwan'],
] as [string, string, string, string][]).map(([symbol, name, currency, region]) => ({
  symbol,
  name,
  market: 'GLOBAL' as Market,
  assetClass: 'saham' as AssetClass,
  currency,
  region,
}))

// ---------------------------------------------------------------------------
// Indeks
// ---------------------------------------------------------------------------

/**
 * Indeks dunia, bukan hanya Indonesia dan Amerika.
 *
 * Dua alasan. Pertama, IHSG tidak bergerak sendirian: arah bursa Asia semalam
 * sebelumnya sering menjelaskan pembukaannya. Kedua, kekuatan relatif hanya
 * berarti bila ada pembandingnya, dan tiap saham dibandingkan terhadap indeks
 * pasarnya sendiri, bukan terhadap indeks negara lain.
 */
const INDEKS: CatalogueEntry[] = [
  ['^JKSE', 'IHSG', 'IDR', 'Indonesia'],
  ['^GSPC', 'S&P 500', 'USD', 'Amerika Serikat'],
  ['^IXIC', 'Nasdaq Composite', 'USD', 'Amerika Serikat'],
  ['^DJI', 'Dow Jones', 'USD', 'Amerika Serikat'],
  ['^RUT', 'Russell 2000', 'USD', 'Amerika Serikat'],
  ['^VIX', 'VIX', 'USD', 'Amerika Serikat'],
  ['^N225', 'Nikkei 225', 'JPY', 'Jepang'],
  ['^HSI', 'Hang Seng', 'HKD', 'Hong Kong'],
  ['000001.SS', 'Shanghai Composite', 'CNY', 'China'],
  ['^STI', 'Straits Times', 'SGD', 'Singapura'],
  ['^KLSE', 'FTSE Bursa Malaysia KLCI', 'MYR', 'Malaysia'],
  ['^SET.BK', 'SET Index', 'THB', 'Thailand'],
  ['^KS11', 'KOSPI', 'KRW', 'Korea Selatan'],
  ['^TWII', 'TAIEX', 'TWD', 'Taiwan'],
  ['^NSEI', 'Nifty 50', 'INR', 'India'],
  ['^BSESN', 'Sensex', 'INR', 'India'],
  ['^AXJO', 'ASX 200', 'AUD', 'Australia'],
  ['^FTSE', 'FTSE 100', 'GBP', 'Inggris'],
  ['^GDAXI', 'DAX', 'EUR', 'Jerman'],
  ['^FCHI', 'CAC 40', 'EUR', 'Prancis'],
  ['^STOXX50E', 'Euro Stoxx 50', 'EUR', 'Zona Euro'],
  ['^BVSP', 'Bovespa', 'BRL', 'Brasil'],
  ['DX-Y.NYB', 'Indeks Dolar AS', 'USD', 'Global'],
].map(([symbol, name, currency, region]) => ({
  symbol,
  name,
  market: 'GLOBAL' as Market,
  assetClass: 'indeks' as AssetClass,
  currency,
  region,
}))

// ---------------------------------------------------------------------------
// Mata uang
// ---------------------------------------------------------------------------

/**
 * Pasangan valas dari Yahoo (`USDIDR=X`). Mata uang di belakang garis miring
 * adalah mata uang harganya, jadi itu yang dicatat sebagai `currency`.
 *
 * Rupiah lebih dulu: pembaca di Indonesia menanyakan "dolar sekarang
 * berapa", baru kemudian pasangan utama dunia. CNYIDR=X tidak dimasukkan —
 * Yahoo hanya punya satu candle untuknya.
 */
const MATA_UANG: CatalogueEntry[] = ([
  ['USDIDR=X', 'Dolar AS / Rupiah', 'IDR', 'Indonesia'],
  ['EURIDR=X', 'Euro / Rupiah', 'IDR', 'Indonesia'],
  ['SGDIDR=X', 'Dolar Singapura / Rupiah', 'IDR', 'Indonesia'],
  ['JPYIDR=X', 'Yen / Rupiah', 'IDR', 'Indonesia'],
  ['AUDIDR=X', 'Dolar Australia / Rupiah', 'IDR', 'Indonesia'],
  ['GBPIDR=X', 'Pound / Rupiah', 'IDR', 'Indonesia'],
  ['MYRIDR=X', 'Ringgit / Rupiah', 'IDR', 'Indonesia'],
  ['EURUSD=X', 'Euro / Dolar AS', 'USD', 'Global'],
  ['USDJPY=X', 'Dolar AS / Yen', 'JPY', 'Global'],
  ['GBPUSD=X', 'Pound / Dolar AS', 'USD', 'Global'],
  ['AUDUSD=X', 'Dolar Australia / Dolar AS', 'USD', 'Global'],
  ['NZDUSD=X', 'Dolar Selandia Baru / Dolar AS', 'USD', 'Global'],
  ['USDCHF=X', 'Dolar AS / Franc Swiss', 'CHF', 'Global'],
  ['USDCAD=X', 'Dolar AS / Dolar Kanada', 'CAD', 'Global'],
  ['USDCNY=X', 'Dolar AS / Yuan', 'CNY', 'Global'],
  ['USDSGD=X', 'Dolar AS / Dolar Singapura', 'SGD', 'Global'],
  ['USDMYR=X', 'Dolar AS / Ringgit', 'MYR', 'Global'],
  ['USDTHB=X', 'Dolar AS / Baht', 'THB', 'Global'],
  ['USDKRW=X', 'Dolar AS / Won', 'KRW', 'Global'],
  ['USDINR=X', 'Dolar AS / Rupee', 'INR', 'Global'],
] as [string, string, string, string][]).map(([symbol, name, currency, region]) => ({
  symbol,
  name,
  market: 'GLOBAL' as Market,
  assetClass: 'mata_uang' as AssetClass,
  currency,
  region,
}))

// ---------------------------------------------------------------------------
// Obligasi
// ---------------------------------------------------------------------------

/**
 * ETF obligasi, bukan obligasinya langsung: harga obligasi satuan tidak ada di
 * sumber terbuka mana pun, sedangkan ETF punya harga dan volume harian.
 * Imbal hasil Treasury dicatat terpisah sebagai deret makro FRED (DGS10 dan
 * kawan-kawan) dan dibacakan ke komite sebagai konteks.
 *
 * SBN Indonesia belum punya sumber otomatis yang gratis. EMB dan VWOB
 * (obligasi negara berkembang dalam dolar, Indonesia termasuk di dalamnya)
 * adalah pendekatan terdekatnya, bukan penggantinya.
 */
const OBLIGASI: CatalogueEntry[] = ([
  ['SHY', 'Treasury AS 1–3 tahun', 'Amerika Serikat'],
  ['IEF', 'Treasury AS 7–10 tahun', 'Amerika Serikat'],
  ['TLT', 'Treasury AS 20+ tahun', 'Amerika Serikat'],
  ['GOVT', 'Treasury AS seluruh tenor', 'Amerika Serikat'],
  ['TIP', 'Treasury AS terlindung inflasi (TIPS)', 'Amerika Serikat'],
  ['AGG', 'Obligasi AS agregat', 'Amerika Serikat'],
  ['BND', 'Obligasi AS total pasar', 'Amerika Serikat'],
  ['LQD', 'Obligasi korporasi AS layak investasi', 'Amerika Serikat'],
  ['HYG', 'Obligasi korporasi AS imbal hasil tinggi', 'Amerika Serikat'],
  ['EMB', 'Obligasi negara berkembang (USD)', 'Negara berkembang'],
  ['VWOB', 'Obligasi pemerintah negara berkembang (USD)', 'Negara berkembang'],
  ['EMLC', 'Obligasi negara berkembang (mata uang lokal)', 'Negara berkembang'],
  ['BNDX', 'Obligasi internasional (lindung nilai)', 'Global'],
  ['IGOV', 'Obligasi pemerintah internasional', 'Global'],
] as [string, string, string][]).map(([symbol, name, region]) => ({
  symbol,
  name,
  market: 'GLOBAL' as Market,
  assetClass: 'obligasi' as AssetClass,
  currency: 'USD',
  region,
}))

/**
 * Obligasi pemerintah per negara, dari bursa negaranya sendiri. 2821.HK
 * (ABF Pan Asia) memuat obligasi pemerintah Indonesia bersama tujuh negara
 * Asia lain — paling dekat ke SBN yang tersedia gratis, riwayatnya baru
 * sejak 2024.
 */
const OBLIGASI_NEGARA: CatalogueEntry[] = ([
  ['IGLT.L', 'Gilt pemerintah Inggris', 'GBP', 'Inggris'],
  ['SEGA.L', 'Obligasi pemerintah Kawasan Euro', 'EUR', 'Kawasan Euro'],
  ['EXX6.DE', 'Bund Jerman 10 tahun ke atas', 'EUR', 'Jerman'],
  ['148070.KS', 'Obligasi pemerintah Korea 10 tahun', 'KRW', 'Korea Selatan'],
  ['2821.HK', 'Obligasi pemerintah Asia (ABF Pan Asia, termasuk Indonesia)', 'USD', 'Asia'],
] as [string, string, string, string][]).map(([symbol, name, currency, region]) => ({
  symbol,
  name,
  market: 'GLOBAL' as Market,
  assetClass: 'obligasi' as AssetClass,
  currency,
  region,
}))

export const CATALOGUE: CatalogueEntry[] = [
  ...CRYPTO,
  ...MEMECOIN,
  ...EMAS,
  ...KOMODITI,
  ...SAHAM_IDX,
  ...SAHAM_US,
  ...SAHAM_INTERNASIONAL,
  ...INDEKS,
  ...MATA_UANG,
  ...OBLIGASI,
  ...OBLIGASI_NEGARA,
]

export function catalogueFor(market: Market): CatalogueEntry[] {
  return CATALOGUE.filter((entry) => entry.market === market)
}

/** Dipakai worker untuk mengisi nama dan kelas aset saat instrumen belum terdaftar. */
export function catalogueEntry(market: Market, symbol: string): CatalogueEntry | undefined {
  return CATALOGUE.find((entry) => entry.market === market && entry.symbol === symbol)
}
